### ISSUE TITLE
Selection specific sheet doesn't work

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/ExcelProvider#12]
Hi,
Selecting specific sheet from *.xlsx file doesn't work.
![image](https://cloud.githubusercontent.com/assets/3004037/6679848/97a533b8-cc0b-11e4-9c93-17b14eca3dcd.png)

When I access first spreadsheet in the same file it works
```FSharp
type Sheet1 = ExcelFile< @"..\FileStorage\test.xlsx", "Sheet1">
//or
//type Sheet = ExcelFile< @"..\FileStorage\test.xlsx">
```

**Comment by WallaceKelly** [comment]
I found that adding an exclamation mark is a workaround:

    type Sheet = ExcelFile< @"c:\temp\Library2\test.xlsx", "Sheet2!" >

![sheet2](https://cloud.githubusercontent.com/assets/698424/6680205/85994f1e-cc2a-11e4-90dd-3d7974e77bf7.png)

**Comment by dmitry-a-morozov** [comment]
Thanks. It works.
