### ISSUE TITLE
Cannot access columns where headers are multiline-cells 

### ISSUE THREAD

**Issue by ntr** [fsprojects/ExcelProvider#19]
If header cell has multiline content type provider generates multiline property name. Code that accesses these properties does not compile.

I am getting something like:

```
[for x in book.Data -> x.``this
is 
a test``]
```

**Comment by ntr** [comment]
Added PR #20 with a fix, unfortunately build is failing on CI server

**Comment by abhiranjankumar00** [comment]
Hi, is there any improvements here?

**Comment by forki** [comment]
Let me check if I can merge the PR

**Comment by pbbwfc** [comment]
This issue was moved to pbbwfc/ExcelProvider4#1

**Comment by forki** [comment]
Should be fixed on nuget.

**Comment by pbbwfc** [comment]
Sorry about the move message - I was trying to take a copy for my Fork and incorrectly ran a tool which tried to move rather than copy the issue.

I intend to look at this issue in my fork and see if I can fix it.

**Comment by forki** [comment]
fixing is nice, but you should still keep the issue / disucssion here.

**Comment by pbbwfc** [comment]
Sorry again - my mistake - I will definitely put the discussion here once I have found something useful.

(I have done some work on the gh-pages - let me know if you think it would be useful to use these changes.)

**Comment by forki** [comment]
please submit docs changes as Prs to https://github.com/fsprojects/ExcelProvider/blob/master/docs/content/index.fsx

the gh-pages branch is automatically generated from there.

**Comment by pbbwfc** [comment]
I tried this and could not find a problem. It also seems to be already included in the tests - see test 
    
    ``Multiline column name should be converted to a single line``

I tried a slightly more complex test with a four line header:

      rows.[0].``this\nis \na\ntest``
and it seemed to work OK.

Is there an example that does not work or should it be closed?
