### ISSUE TITLE
Please update ProvidedTypes.fs for Mono 5.0 #82

### ISSUE THREAD

**Issue by dsyme** [fsprojects/ExcelProvider#42]
Please update to use the latest version of ProvidedTypes.fs, as described in fsprojects/FSharp.TypeProviders.StarterPack#121

**Comment by sergey-tihon** [comment]
@JohnDoeKyrgyz Could you please re-release package on NuGet?
Sorry, I accidentally pushed the fix to the repo indead proper PR.

**Comment by JohnDoeKyrgyz** [comment]
NuGet package is updated.

**Comment by dsyme** [comment]
Thanks!
