### ISSUE TITLE
Use FSharp.TypeProviders.SDK

### ISSUE THREAD

**Issue by Jand42** [fsprojects/ExcelProvider#52]
### Description

Currently the project uses a version of `FSharp.TypeProviders.StarterPack` which seems to not have correct redirecting of `FSharp.Core` references to the one used by the compiling project.

### Repro steps

If you have latest F# tools installed which uses an `FSharp.Core` with assembly version `4.4.3.0`, the TP currently generates a reference to that, even if the project itself references a lower version.

### Expected behavior

`FSharp.Core` assembly references redirected to the one used by the compiling project. This should be handled correctly by current implementation in `FSharp.TypeProviders.SDK`.

### Actual behavior

Failing to find `FSharp.Core` version `4.4.3.0` at runtime although the project was not referencing it.

### Known workarounds

Update project to use latest FSharp.Core. Add downwards assembly redirects to `app/web.config`.

### Related information 

* Operating system: Windows
* NuGet release: `ExcelProvider 0.8.2`

**Comment by dsyme** [comment]
Fixed, but not yet released
