### ISSUE TITLE
no public type provider classes were found

### ISSUE THREAD

**Issue by mfcd** [fsprojects/ExcelProvider#6]
I get the following:

Referenced assembly 'C:...\packages\ExcelProvider.0.1.0\lib\net40\ExcelProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.ComplierServices.TypeProviderAssemblyAttribute' but no public type provider classes were found

This error is generated by:

'''
# r @"C:...\packages\ExcelProvider.0.1.0\lib\net40\ExcelProvider.dll"

'''

could you point me in the right direction fixing this?
Thank you

Btw, what is the difference between the ExcelProvider and FSharpx.TypeProviders.Excel ?

**Comment by NickJosevski** [comment]
I hit this error attempting to build it targeting .NET Framework 4.0 (via some msbuild scripts), changing to build in our intended 4.5.1 fixed this.

**Comment by goswinr** [comment]
I somtimes have the same problem
