### ISSUE TITLE
Assembly named ExcelProvider.RunTime instead of ExcelProvider

### ISSUE THREAD

**Issue by mathias-brandewinder** [fsprojects/ExcelProvider#65]
### Description

The assembly from the nuget package is named `ExcelProvider.Runtime.dll`, which disagrees with the current documentation, and seems accidental/odd. Either the docs need to be updated (see issue #64) or the name is incorrect. I presume the name is incorrect, but I didn't want to touch anything before confirming what the expected behavior was.

### Repro steps
Please provide the steps required to reproduce the problem

Install the nuget package via paket
Packages folder contains `ExcelProvider/lib/net45/ExcelProvider.Runtime.dll`

### Expected behavior

Based on the current documentation and project name, I would expect the dll to be named `ExcelProvider.dll`

### Actual behavior

dll is named `ExcelProvider.Runtime.dll`

### Known workarounds

Use `#r "somePath/ExcelProvider/lib/net45/ExcelProvider.Runtime.dll"` instead of what the docs suggest.

**Comment by sergey-tihon** [comment]
Projects looks migrated to new TP template and assembly names are correct.
So this probably means that docs require some love

**Comment by quintusm** [comment]
@dsyme  did the migration to new template in September.  The published documentation on the website is out of date as per #65.  I haven't had time to figure out the process to publish correct documentation.  I believe the documentation in the git repository is correct, but not published.

**Comment by sergey-tihon** [comment]
Release docs as easy as to call `build.cmd ReleaseDocs` from the root of the repo.
I did just it from current `master` - https://github.com/fsprojects/ExcelProvider/commit/a3d868bcb590313cdb591cce484aa4deb4f8feaf
but seems that docs are out of date ...

**Comment by quintusm** [comment]
@sergey-tihon  I will spend some time to work through it and try to bring it up to date.

**Comment by quintusm** [comment]
I have updated the documentation and published to live.  Marking this issue as closed.
