### ISSUE TITLE
cannot find designtime dll

### ISSUE THREAD

**Issue by dgrimmin** [fsprojects/ExcelProvider#66]
### Description
With the change to version 1.0.x the F# interactive is not able to find the designtime dll. It searches in the lib directory while it should be looking in the typeproviders directory, 

### Repro steps

Reference the runtime dll and open FSharp.Interop.Excel . The fsi will be complaining about the TypeProviderAssembly attribute refering to a designtime dll.

### Expected behavior

Automatic resolving of path to designtime dll

### Actual behavior

Cannot find designtime dll.

### Known workarounds

Copy content of typeproviders directory to lib directory.

### Related
Maybe is possible to amend the 
[<TypeProviderAssembly("ExcelProvider.DesignTime.dll")>]
statement in ExcelProvider.Runtime.fs

**Comment by dgrimmin** [comment]
Upgrading to F#4.5 solved the issue. Issue is closed.

**Comment by natsukagami** [comment]
I'm still having this issue. On linux, with F# 4.5

```
error FS3031 : The type provider '/home/user/.nuget/packages/excelprovider/1.0.1/lib/netstandard2.0/ExcelProvider.Runtime.dll' reported an error : Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'ExcelProvider.DesignTime.dll' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/home/user/project/src/App/App.fsproj]
```

**Comment by quintusm** [comment]
With the release of v2.0.0 this issue should be resolved.  Please comment if anybody still encounters the issue with version 2.0

**Comment by quintusm** [comment]
I am closing this issue as it no longer seems to be a problem.
@natsukagami if you still experience this issue let me know and I will look at it again
