### ISSUE TITLE
Cannot load ExcelDataReader

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/ExcelProvider#67]
### Description

未能加载文件或程序集“ExcelDataReader, Version=3.4.1.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa”或它的某一个依赖项。系统找不到指定的文件。

### Related information 

* Operating system: Windows 10 18334
* Branch: 1.0.1, 1.0.0, 0.9.1
* .NET CORE 2.2
* FSharp.Core 4.6
*  TargetFramework: net471
    Platforms: x86

**Comment by giuliohome** [comment]
Any news? I'm having the same issue on .Net Framework too. 
As a workaround, should I manually add this dependency to the project, right?
Please, confirm, thanks.

**Comment by albertwoo** [comment]
I use paket, and I have to set specific version like below:
```
nuget ExcelProvider 1.0.1
nuget ExcelDataReader 3.6.0
nuget ExcelDataReader.DataSet 3.6.0
```

**Comment by giuliohome** [comment]
I don't use paket but it has a documentation about assembly bindings:
 https://fsprojects.github.io/Paket/dependencies-file.html#Controlling-assembly-binding-redirects

**Comment by mjarosie** [comment]
Had the same issue. I was able to use this package after invoking:

```
dotnet add package ExcelDataReader --version 3.4.1.0
dotnet add package ExcelDataReader.DataSet --version 3.4.1.0
```

which seems like a quick fix. I'm quite new to the .NET ecosystem, shouldn't these dependencies be handled implicitly when installing the `ExcelProvider` package?

**Comment by quintusm** [comment]
Hi @mjarosie .

Yes it should, but for some reason it doesn't

Will have another look at it to see if i can fix this.

**Comment by halcwb** [comment]
@quintusm Any update on this issue? When running code from a script (using paket generate-load-scripts), all works fine. but when trying to use the code from another project, the above error occurs.

**Comment by quintusm** [comment]
HI @halcwb 

Unfortunately this issue still exists.  The nuget package currently specifically targets net45 and netstandard2.0 so if you target those platforms it brings down the correct dependencies. On other platforms is doesn't bring down the required packages and you get the runtime issues you are experiencing. The workaround currently is as follows:
Manually add dependencies to the following nuget packages in addition to  ExcelProvider:
- ExcelDataReader
-ExcelDataReader.DataSet
-System.Text.Encoding.CodePages ( for core and standard projects, not necessary on full framework projects)

The version number redirects should be handled automatically if you do this.

Hope this helps

I am working on new versions which should alleviate this. However, I need to update to FAKE5 first to sort out some issues with building and that is quite a large change and I have limited time available for this.

**Comment by quintusm** [comment]
Version 2.0.0 is released.  This version is now built for netstandard2.0 only, and this issue should now be resolved.  Closing this issue.
