### ISSUE TITLE
Implement ability to load data via a Stream

### ISSUE THREAD

**Issue by ksigmund** [fsprojects/ExcelProvider#71]
### Description

I'd like to be able to load data from a `System.IO.Stream`

For context, I am trying to load data while running inside an Azure Function with a BlobStorage trigger.  At that point, I have access to the data I need in the form of a stream.

The workaround (I think) is to write the data out to temp storage and then read it back in using the facility provided (i.e. by providing the file path).  If an overload can take a stream, then the workaround is unnecessary.

**Comment by plainionist** [comment]
Pull request submitted: https://github.com/fsprojects/ExcelProvider/pull/82

**Comment by quintusm** [comment]
@ksigmund this functionality has been added by @plainionist as mentioned above and is included in version 2.0.0 which has been published now.  You can have a look at the test code to see it in action.
